[tool.poetry]
name = "indeed"
version = "0.1.0"
description = ""
authors = ["tomizap <zaptom.pro@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
